name: Vercel Deployment

on:
  workflow_call:
    secrets:
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true
      RESEND_API_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run:
          vercel --token=${{ secrets.VERCEL_TOKEN }} pull --yes --confirm --environment=production \
          --org-id=${{ secrets.VERCEL_ORG_ID }} \
          --project-id=${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project Artifacts
        run: vercel --token=${{ secrets.VERCEL_TOKEN }} build --prod \
          --org-id=${{ secrets.VERCEL_ORG_ID }} \
          --project-id=${{ secrets.VERCEL_PROJECT_ID }}
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

      - name: Deploy Project Artifacts to Vercel
        run:
          vercel --token=${{ secrets.VERCEL_TOKEN }} deploy --prebuilt --prod \
          --org-id=${{ secrets.VERCEL_ORG_ID }} \
          --project-id=${{ secrets.VERCEL_PROJECT_ID }}
