name: Vercel Deployment

on:
  workflow_call:
    secrets:
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true
      RESEND_API_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          vercel pull --yes \
            --environment=production \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          vercel build --prod \
            --token=${{ secrets.VERCEL_TOKEN }}
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy --prebuilt --prod \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --org-id=${{ secrets.VERCEL_ORG_ID }} \
            --project-id=${{ secrets.VERCEL_PROJECT_ID }}
